### ISSUE TITLE
Moving Infomation from the old Google doc

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft-Documentation#2]
As Raga and I have been fairly busy lately, I have decided to create an issue here incase anyone decides they want to start moving the infomation from our WIP Wiki doc to this github if anyone fancies it :)
https://docs.google.com/document/d/1VfEx2Pd3ttRso2bnO1I7y2QkHMVwqQnKVDT_N8tZez8/

If you want/need any editing perms on that document, just message Raga BM or I on the BC Forums or ask us in IRC.

**Comment by PyroTornado** [comment]
I wouldn't mind moving some of the information to the documentation. Is it up to date with the current build of buildcraft?

**Comment by LuigiHutch** [comment]
Most of the info is still relevant as of 7.2.x even though it was written for 7.1.x. I would have to ask @AlexIIL if this would still be relevant or useful as a lot of the mod is being rewritten for 8.0.x.

**Comment by LuigiHutch** [comment]
BC is currently in progess of adding an ingame guide, Alex said not to bother with it was it wont be useful:
'I don't think it will be useful, but it depends on how well the guide book text transitions to the web version
(AEnterprise was planning to help make a conversion thingy to put it into the web version)'
